FROM adoptopenjdk/openjdk11:latest
ENV KEYCLOAK_CLIENT null
ENV KEYCLOAK_REALM null
ENV DB_URL null
ENV DB_USER null
ENV DB_PASSWORD null
ENV KEYCLOAK_URL null
ENV KEYCLOAK_SECRET null
ENV USER_URL null
ENV SSL_KEY null

ARG JAR_FILE=build/libs/alert-covid-service-location-*.jar


WORKDIR /opt/app

COPY ${JAR_FILE} service_location.jar
EXPOSE 8091
ENTRYPOINT java -DSSL_KEY=$SSL_KEY -DUSER_URL=$USER_URL -DKEYCLOAK_CLIENT=$KEYCLOAK_CLIENT -DKEYCLOAK_REALM=$KEYCLOAK_REALM -DDB_URL=$DB_URL -DDB_USER=$DB_USER -DDB_PASSWORD=$DB_PASSWORD -DKEYCLOAK_URL=$KEYCLOAK_URL -DKEYCLOAK_SECRET=$KEYCLOAK_SECRET -jar service_location.jar